//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.04 at 09:23:25 AM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.eigames.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.eigames;
